using Demo.Sealed;
using Demo.Static;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Demo.Partial
{
	// Auto-Generated By EF-Core
	internal partial class Employee
	{
		public int Id { get; set; }
		public string? Name { get; set; }
		public int Age { get; set; }

		// Partial Method 
		internal partial void Print(int x);

		public void DoSomeCode()
		{
			Console.WriteLine("Hello From AutoGenerated File");
			Print(10);
		}
	}
}
