using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Demo
{
	internal class Car
	{
		#region Attributes
		private int id = default;
		private string? model = default;
		private double speed = default;
		#endregion


		#region Properties
		public int Id
		{
			get { return id; }
			set { id = value; }
		}
		public string? Model
		{
			get { return model; }
			set { model = value; }
		}
		public double Speed
		{
			get { return speed; }
			set { speed = value; }
		}

		#endregion

		#region Methods
		public override string ToString()
		{
			return $"Id = {Id}\nModel = {Model}\nSpeed = {Speed}";
		}
		#endregion

		#region Constructors
		//// Empty Parameterless constructor (Default Constructor ) 
		//// Auto-Generated By Compiler
		//public Car()
		//{

		//}

		#region Constructor Overloading 
		public Car(int id, string? model, double speed)
		{
			this.id = id;
			this.model = model;
			this.speed = speed;
			Console.WriteLine("1st Ctor");
		}
		// Compiler Will No Longer Generate Empty Parameterless constructor.

		public Car(int id, string? model):this(id, model, 190) 
		{
			//this.id = id;
			//this.model = model;
			//this.speed = 290;
			Console.WriteLine("2nd Ctor");
		}

		public Car(int id):this(id , "Audi" , 190)
		{	
			//this.id = id;
			//this.model = "Audi";
			//this.speed = 190;
			Console.WriteLine("3rd Ctor");
		} 
		#endregion


		#endregion
	}
}
